### ISSUE TITLE
Client updates and backward compatibility

### ISSUE THREAD

**Issue by matthieuauger** [Yousign/yousign-api-client-php#4]
Hi,

I am currently implementing Yousign on a Symfony 2.7 project.
I would like to use this official client, but there are some limitations with the current implementation.

For example, the constructor takes a path for parameter and only manage .ini files. In Symfony, the standard file format is .yml, but the current implementation prevents me to use it.

I see 3 options : 

- Make a Pull Request to give the constructor an array of options, but maintain backward compatibility for the existing implementation (if it's a string, continue to parse file as .ini file)
- Create a 2.0 branch which breaks backward compatibility and remove the .ini parsing
- Maybe you don't agree with this, and I should create my own client, but I'd prefer improving the official one

What's your opinion on this ?
 
Thanks for your work.

**Comment by ke20** [comment]
Hi, 

The parameters file is not an obligation.
You could use the setters as an alternative way.

For example, you could create a service for the client like this :

```yml
yourcompany.client.yousign:
    class: \YousignAPI\YsApi
    calls:
        - [ setApiKey, [ %ys_api_key% ] ]
        - [ setEnvironment, [ %kernel.env% ] ]
```

And after in your code :

```php
$client = $this->get('yourcompany.client.yousign');
$client->setLogin('username');
$client->setPassword($client->encryptPassword('password'));

// Use the client
// $client->initCoSign(...);
```

This is a possible solution.
